name: Zeek nightly build

on:
  schedule:
  - cron: 30 6 * * 1

jobs:
  test-nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: zeek/action-zkg-install@v2
      with:
        pkg: ${{ github.server_url }}/${{ github.repository }}
        pkg_sysdeps: libfuzzy-dev libtlsh-dev
        zeek_version: zeek-nightly
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: zkg-logs
        path: ${{ github.workspace }}/.action-zkg-install/artifacts
